name: "Runs on a PR to main"

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  run_unit_tests:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: "Just testing"
        run: echo "Hello world"
